{"name": "test_login", "status": "broken", "statusDetails": {"message": "NameError: name 'SeleniumWrapper' is not defined", "trace": "tp = <class 'NameError'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n                raise value.with_traceback(tb)\n>           raise value\n\n/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py:693: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py:693: in reraise\n    raise value\n/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py:693: in reraise\n    raise value\n/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/allure_commons/_allure.py:169: in __call__\n    return self._fixture_function(*args, **kwargs)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def fin():\n>       driver = SeleniumWrapper().driver\nE       NameError: name 'SeleniumWrapper' is not defined\n\n../conftest.py:37: NameError"}, "attachments": [{"name": "stdout", "source": "06d6b07b-666b-4183-88cb-7caccb202bb2-attachment.txt", "type": "text/plain"}], "start": 1559918641666, "stop": 1559918641666, "uuid": "872e3043-f039-4d30-b870-4fc7fd22e13e", "historyId": "1d6c5e711b29cf7bad43b6e24d6adc90", "fullName": "tests.test#test_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test"}, {"name": "host", "value": "Work-Mac-Mini.local"}, {"name": "thread", "value": "90263-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test"}]}