{"uuid": "ef20b6d9-e294-4b7b-9f51-69247bde93d5", "children": ["fedc2ea1-bc40-4813-a8a7-9c69f04509a0", "f7f104f0-24bb-4cc4-bb14-597d1769aae4", "6d5e0c88-c31b-45bc-8454-a6e97eca70ab"], "befores": [{"name": "app", "status": "passed", "start": 1559916918543, "stop": 1559916927588}], "afters": [{"name": "app::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Session' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/allure_commons/_allure.py\", line 169, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 802, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/ace/Documents/GitHub/epam_ta/pom/conftest.py\", line 19, in app\n    if request.node.rep_call.failed:\n"}, "start": 1559916937730, "stop": 1559916937734}], "start": 1559916918543, "stop": 1559916937734}