{"uuid": "4ba905a0-81cd-42cd-8fa7-3df2af9b5b21", "children": ["2d7e7614-f7af-4555-803f-c52dee1ef65f", "a9a22604-8381-47f8-8db4-287c3645dafa", "f8b229bd-8323-4e5a-bb39-b43c6e299521"], "befores": [{"name": "app", "status": "passed", "start": 1559916801901, "stop": 1559916811407}], "afters": [{"name": "app::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Session' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/allure_commons/_allure.py\", line 169, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 802, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/ace/Documents/GitHub/epam_ta/pom/conftest.py\", line 19, in app\n    if request.node.rep_call.failed:\n"}, "start": 1559916821689, "stop": 1559916821692}], "start": 1559916801901, "stop": 1559916821692}