{"name": "test_eggs", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "@pytest.mark.usefixtures(\"take_screenshot_when_failure\")\n    def test_eggs():\n>       assert False\nE       assert False\n\ntest.py:32: AssertionError"}, "start": 1559915316614, "stop": 1559915316615, "uuid": "d0f8b7e4-b98c-48e0-870c-89666769e858", "historyId": "7d82cc76e1d8962d75be6782ce224789", "fullName": "tests.test#test_eggs", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test"}, {"name": "host", "value": "Work-Mac-Mini.local"}, {"name": "thread", "value": "89359-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test"}]}