{"uuid": "8e3d4939-966a-4523-a89d-58050f186ca6", "children": ["4d93d943-a718-4bb0-aa28-f5dd22bc3820", "d81724c0-15d6-4e8e-8f30-be3c2c39412c", "6a34fe29-a8b0-47b1-8df4-a3ca806b8033"], "befores": [{"name": "app", "status": "passed", "start": 1559918392690, "stop": 1559918402230}], "afters": [{"name": "app::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Session' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/allure_commons/_allure.py\", line 169, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 802, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/ace/Documents/GitHub/epam_ta/pom/conftest.py\", line 19, in app\n    if request.node.rep_call.failed:\n"}, "start": 1559918412251, "stop": 1559918412255}], "start": 1559918392690, "stop": 1559918412255}