{"uuid": "6bc86598-3ccb-408d-9471-efca8bfb5116", "children": ["b7765f31-4526-4b5e-9219-4f4c4cadd367", "e5fd2216-e722-44ad-a9af-bc756c5906fa", "4a320de8-013d-45c9-9559-c626909cdb7a"], "befores": [{"name": "app", "status": "passed", "start": 1559915670583, "stop": 1559915679535}], "afters": [{"name": "app::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Session' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/allure_commons/_allure.py\", line 169, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 802, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/ace/Documents/GitHub/epam_ta/pom/conftest.py\", line 18, in app\n    if request.node.rep_call.failed:\n"}, "start": 1559915689471, "stop": 1559915689473}], "start": 1559915670583, "stop": 1559915689473}